version: "1"
services:
  orion-site-service:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    image: orion:latest
    container_name: orion-container
    command: gunicorn -w 2 'server.web:app' -b '0.0.0.0:5000'
    restart:
      on-failure
      # command: flask run --host=0.0.0.0 --port=5000 --debug
    ports:
      - 5000:5000
    environment:
      - AMBIENTE=dev
      - APP_SESSION_URL=redis://orion-redis-service:6379/0
      - APP_BROKER_URL=redis://orion-redis-service:6379/1
      - APP_BACKEND_URL=redis://orion-redis-service:6379/1
      - APP_CACHE_URL=redis://orion-redis-service:6379/2
      # - LOG_LEVEL=DEBUG
    volumes:
      - orion-static-volume:/home/non-root/client/public
    networks:
      - orion-network

volumes:
  orion-static-volume:
    name: orion-static-volume

networks:
  orion-network:
    name: orion-network
    external: false
