const imoveis = [
    {
      codigo: 1,
      status: 1,
      captacao: "site",
      nome: "Apartamento 3 quartos",
      endereco: "Rua das Flores",
      numero: 123,
      bairro: "Jardim das Flores",
      cidade: "São Paulo",
      estado: "SP",
      cep: "12345-678",
      preco: "R$ 1.000.000,00",
      condominio: "R$ 500,00",
      iptu: "R$ 100,00",
      area: "100m²",
      quartos: 3,
      suites: 1,
      banheiros: 2,
      responsavel: "Dani",
      imagemUrl: "https://upload.wikimedia.org/wikipedia/commons/9/95/Imagens_da_Cidade_de_S%C3%A3o_Paulo_e_Zool%C3%B3gico_da_Capital_Paulista._%2847480340301%29.jpg"
    },
    {
      codigo: 2,
      status: 2,
      captacao: "site",
      nome: "Casa 4 quartos",
      endereco: "Avenida Central",
      numero: 456,
      bairro: "Centro",
      cidade: "Rio de Janeiro",
      estado: "RJ",
      cep: "54321-987",
      preco: "R$ 800.000,00",
      condominio: "R$ 0,00",
      iptu: "R$ 200,00",
      area: "200m²",
      quartos: 4,
      suites: 2,
      banheiros: 3,
      responsavel: "João",
    },
    {
      codigo: 3,
      status: 3,
      nome: "Sobrado 2 quartos",
      endereco: "Rua da Praia",
      numero: 789,
      bairro: "Beira Mar",
      cidade: "Fortaleza",
      estado: "CE",
      cep: "98765-432",
      preco: "R$ 500.000,00",
      condominio: "R$ 100,00",
      iptu: "R$ 50,00",
      area: "150m²",
      quartos: 2,
      suites: 1,
      banheiros: 2,
      responsavel: "Maria",
    },
    {
      codigo: 4,
      status: 1,
      nome: "Apartamento 2 quartos",
      endereco: "Avenida dos Pássaros",
      numero: 101,
      bairro: "Bela Vista",
      cidade: "São Paulo",
      estado: "SP",
      cep: "54321-123",
      preco: "R$ 750.000,00",
      condominio: "R$ 300,00",
      iptu: "R$ 80,00",
      area: "90m²",
      quartos: 2,
      suites: 1,
      banheiros: 2,
      responsavel: "Carlos",
    },
    {
      codigo: 5,
      status: 2,
      nome: "Cobertura 3 quartos",
      endereco: "Rua da Montanha",
      numero: 567,
      bairro: "Alto da Serra",
      cidade: "Belo Horizonte",
      estado: "MG",
      cep: "87654-321",
      preco: "R$ 1.200.000,00",
      condominio: "R$ 600,00",
      iptu: "R$ 120,00",
      area: "180m²",
      quartos: 3,
      suites: 2,
      banheiros: 3,
      responsavel: "Ana",
    },
    {
      codigo: 6,
      status: 3,
      nome: "Casa 5 quartos",
      endereco: "Rua do Campo",
      numero: 111,
      bairro: "Zona Rural",
      cidade: "Curitiba",
      estado: "PR",
      cep: "76543-210",
      preco: "R$ 900.000,00",
      condominio: "R$ 0,00",
      iptu: "R$ 150,00",
      area: "250m²",
      quartos: 5,
      suites: 2,
      banheiros: 4,
      responsavel: "Luiz",
    },
    {
      codigo: 7,
      status: 1,
      nome: "Apartamento 1 quarto",
      endereco: "Avenida do Parque",
      numero: 222,
      bairro: "Parque das Flores",
      cidade: "Porto Alegre",
      estado: "RS",
      cep: "98765-432",
      preco: "R$ 400.000,00",
      condominio: "R$ 200,00",
      iptu: "R$ 60,00",
      area: "60m²",
      quartos: 1,
      suites: 1,
      banheiros: 1,
      responsavel: "Paula",
    },
    {
      codigo: 8,
      status: 2,
      nome: "Casa 3 quartos",
      endereco: "Rua das Árvores",
      numero: 333,
      bairro: "Bosque Verde",
      cidade: "Salvador",
      estado: "BA",
      cep: "76543-210",
      preco: "R$ 600.000,00",
      condominio: "R$ 300,00",
      quartos: 2,
      suites: 0,
      responsavel: "Ale",
    },
    {
      codigo: 9,
      status: 1,
      nome: "Apartamento 2 quartos",
      endereco: "Avenida dos Pássaros",
      numero: 101,
      bairro: "Bela Vista",
      cidade: "São Paulo",
      estado: "SP",
      cep: "54321-123",
      preco: "R$ 750.000,00",
      condominio: "R$ 300,00",
      iptu: "R$ 80,00",
      area: "90m²",
      quartos: 2,
      suites: 1,
      banheiros: 2,
      responsavel: "Carlos",
    },
]

export default imoveis;
  